import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { FileBlob, PresentationFile } from "@oai/artifact-tool";

const ROOT = "/Users/khairuladib/MATLAB-Drive/Kuliah/computational-physics-course";
const WEEK = `${ROOT}/Week06`;
const BUILD = `${WEEK}/.agent/lecture-slides/editable-build`;
const MASTER = `${ROOT}/.agent/lecture-slide-system/masters/PHY4605_Editable_Slide_Master.pptx`;
const FINAL = `${BUILD}/final-output/Lecture_Slides_Week06.finalized.pptx`;
const DELIVERY = `${WEEK}/Lecture_Slides_Week06.pptx`;
const RENDER = `${BUILD}/artifact-renders`;
const E = `${WEEK}/.agent/lecture-slides/equations`;
const A = `${WEEK}/.agent/matlab/assets`;
const SKILL = "/Users/khairuladib/.codex/plugins/cache/openai-primary-runtime/presentations/26.903.11416/skills/presentations";
const NODE_PY = "/Users/khairuladib/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3";
const C = { navy:"#0B2B4C", charcoal:"#3F4B57", muted:"#697684", blue:"#2F6DB2", teal:"#2A9D9F", green:"#3E8E45", gold:"#C98A16", purple:"#6F4B9B", rule:"#AAB4BE", white:"#FFFFFF", paleNavy:"#F4F8FC", paleBlue:"#EEF5FD", paleGold:"#FFF7E6", paleValid:"#F0FAF7", palePurple:"#F5F1FB", paleRed:"#FFF2F2", paleNeutral:"#F7F9FB" };
const L = { opening:"/ppt/slideLayouts/slideLayout2.xml", t1:"/ppt/slideLayouts/slideLayout3.xml", t2:"/ppt/slideLayouts/slideLayout4.xml", t3:"/ppt/slideLayouts/slideLayout5.xml" };
function nl(){return {style:"solid",fill:"none",width:0};}
function txt(s,n,t,x,y,w,h,o={}){const z=s.shapes.add({geometry:"textbox",name:n,position:{left:x,top:y,width:w,height:h},fill:"none",line:nl()});z.text=t;z.text.style={fontSize:o.size??28,typeface:o.font??"Nunito",color:o.color??C.charcoal,bold:o.bold??false,alignment:o.align??"left",verticalAlignment:o.valign??"top",lineSpacing:o.spacing??1.03,wrap:o.wrap??"square",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}};return z;}
function box(s,n,x,y,w,h,fill=C.white,line=C.rule){return s.shapes.add({geometry:"roundRect",name:n,position:{left:x,top:y,width:w,height:h},fill,line:{style:"solid",fill:line,width:2},borderRadius:22,shadow:"shadow-none"});}
function line(s,n,x,y,w,h,c=C.navy,wd=3,style="solid"){if(w<0){x+=w;w=-w;}if(h<0){y+=h;h=-h;}return s.shapes.add({geometry:"line",name:n,position:{left:x,top:y,width:w,height:h},fill:"none",line:{style,fill:c,width:wd}});}
function circle(s,n,x,y,d,fill){return s.shapes.add({geometry:"ellipse",name:n,position:{left:x,top:y,width:d,height:d},fill,line:{style:"solid",fill,width:0}});}
function arrow(s,n,x,y,w,h,fill=C.rule){return s.shapes.add({geometry:"rightArrow",name:n,position:{left:x,top:y,width:w,height:h},fill,line:nl()});}
function img(s,n,p,alt,x,y,w,h){return s.images.add({path:p,name:n,alt,fit:"contain",position:{left:x,top:y,width:w,height:h}});}
function ph(s,n,t,style){let z;try{z=s.placeholders.getItem(n);}catch{} if(!z)return txt(s,n,t,style.left,style.top,style.width,style.height,style.text);z.position={left:style.left,top:style.top,width:style.width,height:style.height};z.text=t;z.text.style=style.text;return z;}
function chrome(s,num,title,variant="T1",sub=""){const t3=variant==="T3", size=variant==="T1"?68:variant==="T2"?62:56;ph(s,"title",title,{left:115,top:60,width:1580,height:t3?138:88,text:{fontSize:size,typeface:"Nunito",color:C.navy,bold:true,alignment:"left",verticalAlignment:"top",lineSpacing:.94,wrap:t3?"square":"none",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}}});if(sub)ph(s,"subtitle",sub,{left:115,top:t3?205:152,width:1580,height:44,text:{fontSize:30,typeface:"Nunito",color:C.charcoal,alignment:"left",verticalAlignment:"top",lineSpacing:1,wrap:"none",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}}});ph(s,"slideNumber",String(num),{left:1764,top:976,width:40,height:28,text:{fontSize:22,typeface:"Nunito",color:C.muted,alignment:"right",verticalAlignment:"middle",wrap:"none",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}}});}
function note(s,no,extra=""){s.speakerNotes.textFrame.setText(`Week 06 slide ${no}. Ask students to state the physical quantity and its unit before reading the numerical result.\n\n[Sources]\n- Week06/.agent/lecture-slides/outline.md\n- Week06/.agent/manifests/Week06_Content_Manifest.md\n- Week06/Week06_Lecture_Demonstration_Numerical_Differentiation_of_Vertical_Motion.m\n- PHY4605_Lecture_Slide_Design_Spec.md${extra?`\n- ${extra}`:""}`);s.speakerNotes.setVisible(true);}
function table(s,n,x,y,w,h,values){const t=s.tables.add({name:n,rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,columnWidths:[150,330,280,250],values});t.styleOptions={headerRow:false,bandedRows:false,bandedColumns:false};t.borders.assign({style:"solid",fill:C.rule,width:1});for(let r=0;r<t.rows.length;r++)for(let c=0;c<t.columns.length;c++){const cell=t.getCell(r,c);cell.fill=r===0?C.navy:C.white;cell.text.style={fontSize:r===0?21:25,typeface:"Nunito",color:r===0?C.white:C.charcoal,bold:r===0,alignment:c===0?"left":"center",verticalAlignment:"middle",wrap:"square",autoFit:"shrinkText",insets:{top:8,right:10,bottom:8,left:10}};}return t;}
async function blob(p){const b=await fs.readFile(p);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
async function main(){await fs.mkdir(RENDER,{recursive:true});const p=await PresentationFile.importPptx(await FileBlob.load(MASTER));for(const s of [...p.slides.items])s.delete();const slides=[];const add=(layout)=>{const s=p.slides.add({layoutId:layout});s.setViewportSize(1920,1080);s.background.fill=C.white;slides.push(s);return s;};
// 1
{const s=add(L.opening);ph(s,"title","From Nearby Values\nto an Instantaneous Rate",{left:115,top:245,width:1080,height:210,text:{fontSize:74,typeface:"Nunito",color:C.navy,bold:true,alignment:"left",verticalAlignment:"top",lineSpacing:.94,wrap:"square",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}}});ph(s,"subtitle","Week 6 | Numerical differentiation with vertical motion",{left:115,top:475,width:1180,height:80,text:{fontSize:34,typeface:"Nunito",color:C.charcoal,alignment:"left",verticalAlignment:"top",wrap:"none",autoFit:"shrinkText",insets:{top:0,right:0,bottom:0,left:0}}});txt(s,"tag","PHY4605 Computational Methods in Physics",115,126,760,38,{size:26,color:C.charcoal,bold:true});line(s,"axis",1390,720,0,-410,C.navy,4);line(s,"ground",1260,720,515,0,C.rule,3);circle(s,"marker-t0",1470,470,28,C.gold);circle(s,"marker-next",1540,520,28,C.blue);line(s,"velocity",1450,470,0,-145,C.teal,5);txt(s,"hero-y","vertical position, y",1280,250,280,35,{size:24,color:C.muted});txt(s,"hero-q","How can two nearby values estimate velocity at one instant?",115,860,1450,45,{size:30,color:C.navy,bold:true});note(s,1);}
// 2
{const s=add(L.t1);chrome(s,2,"A derivative is a physical rate","T1","Read the quantity, then derive its unit from the variables");const a=[["position y(t)","velocity dy/dt","m/s",C.blue],["potential V(x)","electric field −dV/dx","V/m",C.teal],["temperature T(t)","cooling rate dT/dt","K/s",C.gold]];a.forEach((q,i)=>{const x=115+i*565;box(s,`rate-${i}`,x,310,500,350,i===0?C.paleBlue:i===1?C.paleValid:C.paleGold,q[3]);txt(s,`rate-in-${i}`,q[0],x+35,365,430,45,{size:32,color:q[3],bold:true,align:"center"});arrow(s,`rate-arrow-${i}`,x+220,432,60,35,C.rule);txt(s,`rate-out-${i}`,q[1],x+35,500,430,46,{size:27,color:C.navy,bold:true,align:"center"});txt(s,`rate-unit-${i}`,q[2],x+35,590,430,43,{size:28,color:C.charcoal,align:"center"});});txt(s,"unit-rule","For y in metres and t in seconds, dy/dt has unit m/s",115,760,1560,55,{size:32,color:C.green,bold:true,align:"center"});note(s,2);}
// 3
{const s=add(L.t1);chrome(s,3,"Numerical differentiation uses two nearby values","T1","A forward difference divides a position change by a time step");img(s,"fd-equation",`${E}/forward-difference.png`,"Forward-difference definition",155,275,780,150);line(s,"xaxis",155,760,720,0,C.charcoal,3);line(s,"yaxis",190,790,0,-440,C.charcoal,3);line(s,"secant",390,635,330,-175,C.blue,5);circle(s,"p0",380,625,22,C.gold);circle(s,"ph",710,450,22,C.blue);txt(s,"t0","t₀",360,785,75,34,{size:24,color:C.gold,bold:true,align:"center"});txt(s,"t0h","t₀ + h",680,785,95,34,{size:24,color:C.blue,bold:true,align:"center"});txt(s,"meaning","numerator: change in position\ndenominator: change in time",1060,410,590,120,{size:31,color:C.charcoal,bold:true});box(s,"unit",1060,600,570,150,C.paleValid,C.teal);txt(s,"unit-label","metres / seconds = m/s",1100,650,490,45,{size:32,color:C.teal,bold:true,align:"center"});note(s,3,"Week06/.agent/lecture-slides/equations/forward-difference.tex");}
// 4
{const s=add(L.t1);chrome(s,4,"A familiar vertical-motion model","T1","Keep the physics fixed while the numerical approximation changes");img(s,"model",`${E}/vertical-motion-model.png`,"Vertical position model",115,285,870,145);const rows=[["y₀","0 m"],["v₀","20 m/s"],["g","9.81 m/s²"],["t₀","1.0 s"]];rows.forEach((r,i)=>{const y=490+i*85;txt(s,`var-${i}`,r[0],1120,y,130,38,{size:30,color:C.blue,bold:true});txt(s,`value-${i}`,r[1],1300,y,280,38,{size:30,color:C.charcoal,bold:true});line(s,`rule-${i}`,1110,y+52,480,0,C.rule,1);});box(s,"assumption",115,690,1475,105,C.paleBlue,C.blue);txt(s,"assume","Assumption: constant gravitational acceleration and negligible air resistance",150,720,1400,42,{size:29,color:C.navy,bold:true,align:"center"});note(s,4,"Week06/.agent/lecture-slides/equations/vertical-motion-model.tex");}
// 5
{const s=add(L.t1);chrome(s,5,"Prediction before computing","T1","At t₀ = 1.0 s, the projectile is still moving upward");box(s,"positive",180,320,440,290,C.paleValid,C.green);txt(s,"p1","positive",220,375,360,55,{size:42,color:C.green,bold:true,align:"center"});txt(s,"p1b","velocity remains upward",220,485,360,52,{size:28,color:C.charcoal,align:"center"});box(s,"less",740,320,440,290,C.paleGold,C.gold);txt(s,"p2","below 20 m/s",775,375,370,55,{size:39,color:C.gold,bold:true,align:"center"});txt(s,"p2b","gravity has reduced the initial speed",775,485,370,52,{size:28,color:C.charcoal,align:"center"});box(s,"check",1300,320,440,290,C.paleRed,"#B3262E");txt(s,"p3","check sign and unit",1335,375,370,55,{size:35,color:"#B3262E",bold:true,align:"center"});txt(s,"p3b","wrong sign or missing m/s needs investigation",1335,485,370,52,{size:26,color:C.charcoal,align:"center"});note(s,5);}
// 6
{const s=add(L.t1);chrome(s,6,"One forward difference by hand","T1","Use h = 0.5 s and retain units in every line");img(s,"fd-hand",`${E}/forward-difference.png`,"Forward difference",125,265,750,125);const steps=[["y(1.0 s)","15.095 m"],["y(1.5 s)","18.96375 m"],["Δy / h","(18.96375 − 15.095) m / 0.5 s"],["vfd(1.0 s)","7.7375 m/s"]];steps.forEach((r,i)=>{const y=435+i*90;txt(s,`hand-l-${i}`,r[0],150,y,300,38,{size:29,color:i===3?C.green:C.navy,bold:true});txt(s,`hand-r-${i}`,r[1],490,y,1050,40,{size:29,color:i===3?C.green:C.charcoal,bold:i===3});line(s,`hand-line-${i}`,150,y+55,1390,0,C.rule,1);});box(s,"hand-result",1120,760,420,90,C.paleValid,C.green);txt(s,"hand-final","7.7375 m/s",1150,785,360,35,{size:30,color:C.green,bold:true,align:"center"});note(s,6,"Week06/.agent/lecture-slides/equations/forward-difference.tex");}
// 7
{const s=add(L.t1);chrome(s,7,"Pseudocode before MATLAB","T1","The algorithm names the model evaluations before code syntax appears");const ps=["choose t₀ and h","evaluate y(t₀)","evaluate y(t₀ + h)","subtract positions","divide by h","compare with reference"];ps.forEach((q,i)=>{const x=115+(i%3)*565,y=300+Math.floor(i/3)*240;circle(s,`step-${i}`,x,y,52,i<4?C.blue:i===4?C.gold:C.teal);txt(s,`step-no-${i}`,String(i+1),x,y+7,52,35,{size:25,color:C.white,bold:true,align:"center"});txt(s,`step-text-${i}`,q,x+75,y+7,400,42,{size:29,color:C.navy,bold:true});if(i%3<2)arrow(s,`step-arrow-${i}`,x+475,y+10,55,32,C.rule);});box(s,"repeat",420,795,1080,75,C.paleGold,C.gold);txt(s,"repeat-text","Repeat only for the supplied step-size array h = [0.5 0.2 0.1 0.05] s",455,815,1010,34,{size:28,color:C.gold,bold:true,align:"center"});note(s,7);}
// 8
{const s=add(L.t1);chrome(s,8,"MATLAB scaffold","T1","Trace the supplied expressions and identify the denominator");box(s,"codebox",115,265,1080,550,C.paleNavy,C.rule);const code="t0_s = 1.0;\nh_s = [0.5 0.2 0.1 0.05];\ny_now_m = y0_m + v0_mps*t0_s - 0.5*g_mps2*t0_s^2;\ny_forward_m = y0_m + v0_mps*(t0_s+h_s) - 0.5*g_mps2*(t0_s+h_s).^2;\nv_forward_mps = (y_forward_m-y_now_m)./h_s;";txt(s,"code",code,150,305,1010,470,{font:"IBM Plex Mono",size:24,color:C.navy,spacing:1.2});const labs=[["TARGET","t0_s",C.blue],["STEP ARRAY","h_s",C.gold],["TWO VALUES","y_now_m and y_forward_m",C.teal],["DIVIDE BY STEP","./h_s",C.green]];labs.forEach((q,i)=>{const y=285+i*125;box(s,`lab-${i}`,1285,y,430,88,i===1?C.paleGold:i===2?C.paleValid:C.paleBlue,q[2]);txt(s,`labt-${i}`,q[0],1310,y+16,380,27,{size:23,color:q[2],bold:true,align:"center"});txt(s,`labb-${i}`,q[1],1310,y+48,380,25,{font:"IBM Plex Mono",size:20,color:C.charcoal,align:"center"});});note(s,8);}
// 9
{const s=add(L.t1);chrome(s,9,"Smaller steps give a more local estimate","T1","Read the table and plot together before interpreting the trend");table(s,"comparison",115,275,1010,380,[["h (s)","forward estimate (m/s)","absolute error (m/s)","relative error (%)"],["0.50","7.7375","2.4525","24.0677"],["0.20","9.2090","0.9810","9.6271"],["0.10","9.6995","0.4905","4.8135"],["0.05","9.94475","0.24525","2.4068"]]);img(s,"step-plot",`${A}/week06_forward_difference_geometry.png`,"MATLAB forward-difference geometry",1170,260,600,420);box(s,"trend",115,730,1560,92,C.paleValid,C.green);txt(s,"trend-text","Over this supplied range, a smaller h makes the secant more local and the measured error smaller",155,760,1480,34,{size:28,color:C.green,bold:true,align:"center"});note(s,9,"Week06/.agent/matlab/assets/week06_forward_difference_geometry.png; MATLAB-generated evidence");}
// 10
{const s=add(L.t1);chrome(s,10,"Analytic validation","T1","Use an independent reference at the same target time");img(s,"analytic",`${E}/analytic-velocity.png`,"Analytic velocity",200,280,730,135);box(s,"reference",1080,275,540,180,C.paleValid,C.green);txt(s,"ref-title","reference at t₀ = 1.0 s",1110,315,480,40,{size:29,color:C.green,bold:true,align:"center"});txt(s,"ref-value","10.19 m/s",1110,375,480,54,{size:42,color:C.navy,bold:true,align:"center"});arrow(s,"check-arrow",800,540,220,55,C.rule);box(s,"num",280,600,520,160,C.paleBlue,C.blue);txt(s,"num-title","smallest supplied h",320,635,440,35,{size:28,color:C.blue,bold:true,align:"center"});txt(s,"num-value","9.94475 m/s",320,690,440,42,{size:34,color:C.navy,bold:true,align:"center"});box(s,"validation",1050,600,580,160,C.paleValid,C.green);txt(s,"valid-title","validation statement",1090,635,500,35,{size:28,color:C.green,bold:true,align:"center"});txt(s,"valid-value","positive and close to the reference",1090,690,500,42,{size:30,color:C.navy,bold:true,align:"center"});note(s,10,"Week06/.agent/lecture-slides/equations/analytic-velocity.tex");}
// 11
{const s=add(L.t1);chrome(s,11,"Simple error with a physical unit","T1","Absolute error keeps m/s; relative error reports a percentage");img(s,"err",`${E}/absolute-error.png`,"Absolute error definition",145,285,800,130);box(s,"abs",180,500,600,220,C.paleBlue,C.blue);txt(s,"abs-head","At h = 0.05 s",220,540,520,38,{size:31,color:C.blue,bold:true,align:"center"});txt(s,"abs-val","0.24525 m/s",220,600,520,54,{size:41,color:C.navy,bold:true,align:"center"});box(s,"rel",1040,500,600,220,C.paleGold,C.gold);txt(s,"rel-head","Relative error",1080,540,520,38,{size:31,color:C.gold,bold:true,align:"center"});txt(s,"rel-val","2.4068%",1080,600,520,54,{size:41,color:C.navy,bold:true,align:"center"});txt(s,"warning","State which estimate and reference you compared",115,800,1560,38,{size:29,color:C.charcoal,bold:true,align:"center"});note(s,11,"Week06/.agent/lecture-slides/equations/absolute-error.tex");}
// 12
{const s=add(L.t1);chrome(s,12,"A finite secant approximates a local tangent","T1","Forward difference uses an interval h, so it estimates rather than reproduces the derivative");img(s,"secant-plot",`${A}/week06_forward_difference_geometry.png`,"MATLAB secant and tangent geometry",180,270,740,510);const pts=[["coarse h","secant spans a larger interval",C.gold,C.paleGold],["smaller h","secant samples closer to t₀",C.blue,C.paleBlue],["derivative","tangent rate at t₀",C.teal,C.paleValid]];pts.forEach((q,i)=>{const y=305+i*150;box(s,`reason-${i}`,1080,y,580,105,q[3],q[2]);txt(s,`reason-h-${i}`,q[0],1110,y+20,180,35,{size:29,color:q[2],bold:true});txt(s,`reason-b-${i}`,q[1],1305,y+18,320,55,{size:25,color:C.charcoal,bold:true});});note(s,12,"Week06/.agent/matlab/assets/week06_forward_difference_geometry.png; MATLAB-generated evidence");}
// 13
{const s=add(L.t2);chrome(s,13,"Working exposure: central difference and error behaviour","T2","Interpret supplied evidence only; no independent central-difference implementation is required");img(s,"central",`${E}/central-difference.png`,"Central-difference definition",130,280,850,130);box(s,"central-note",1080,270,610,190,C.palePurple,C.purple);txt(s,"central-title","symmetric samples",1110,310,550,36,{size:30,color:C.purple,bold:true,align:"center"});txt(s,"central-body","For this quadratic model, the supplied expression matches the analytic derivative to floating-point precision",1120,365,530,72,{size:25,color:C.charcoal,align:"center"});img(s,"errorplot",`${A}/week06_forward_error_vs_step.png`,"MATLAB error versus step-size plot",155,500,760,350);txt(s,"qual","Qualitative reading: an extremely small h is not a universal guarantee of a better answer",1030,600,610,95,{size:31,color:C.purple,bold:true,align:"center"});note(s,13,"Week06/.agent/lecture-slides/equations/central-difference.tex; Week06/.agent/matlab/assets/week06_forward_error_vs_step.png; MATLAB-generated evidence");}
// 14
{const s=add(L.t1);chrome(s,14,"Transfer and exit ticket","T1","Use the same reasoning chain in another familiar physical context");const x=[115,675,1235];[["vertical motion","dy/dt in m/s",C.blue,C.paleBlue],["electric potential","E = −dV/dx in V/m",C.teal,C.paleValid],["cooling","dT/dt in K/s",C.gold,C.paleGold]].forEach((q,i)=>{box(s,`transfer-${i}`,x[i],280,450,190,q[3],q[2]);txt(s,`trh-${i}`,q[0],x[i]+25,325,400,42,{size:31,color:q[2],bold:true,align:"center"});txt(s,`trb-${i}`,q[1],x[i]+25,405,400,40,{size:27,color:C.navy,bold:true,align:"center"});});const ex=[["meaning","What rate or gradient?"],["unit","What unit follows?"],["formula","Which two values?"],["check","What reference validates it?"]];ex.forEach((q,i)=>{const xx=115+i*400;box(s,`exit-${i}`,xx,610,350,190,C.paleNavy,C.rule);txt(s,`exit-h-${i}`,q[0],xx+25,650,300,35,{size:29,color:C.navy,bold:true,align:"center"});txt(s,`exit-b-${i}`,q[1],xx+30,715,290,55,{size:24,color:C.charcoal,bold:true,align:"center"});});note(s,14);}
for(let i=0;i<slides.length;i++){const stem=`slide-${String(i+1).padStart(2,"0")}`;const b=await p.export({slide:slides[i],format:"png",scale:1});await fs.writeFile(`${RENDER}/${stem}.png`,new Uint8Array(await b.arrayBuffer()));await fs.writeFile(`${RENDER}/${stem}.layout.json`,await (await slides[i].export({format:"layout"})).text());}
const montage=await p.export({format:"webp",montage:true,scale:.35});await fs.writeFile(`${BUILD}/artifact-deck-montage.webp`,new Uint8Array(await montage.arrayBuffer()));const insp=await p.inspect({kind:"slide,textbox,shape,image,table,notes,layout",maxChars:250000});await fs.writeFile(`${BUILD}/artifact-tool-inspect.ndjson`,insp.ndjson);await (await PresentationFile.exportPptx(p)).save(`${BUILD}/Week06_candidate.pptx`);
const {finalizePresentation}=await import(pathToFileURL(path.join(SKILL,"container_tools/artifact_tool_utils.mjs")).href);const result=await finalizePresentation({explicitTotalSlideCount:14,workspaceDir:ROOT,candidatePath:`${BUILD}/Week06_candidate.pptx`,finalPath:FINAL,pythonExecutable:NODE_PY,integrityValidatorPath:path.join(SKILL,"container_tools/inspect_presentation_package_integrity.py"),layoutValidatorPath:path.join(SKILL,"container_tools/inspect_presentation_layout_geometry.py"),layoutArgs:["--expected-slide-size-emu","18288000,10287000","--validate-bullet-geometry","--validate-heading-fit"],fontPolicy:{basis:"design",families:["Nunito","IBM Plex Mono"]},verifyArtifactToolImport:true,receiptPath:`${BUILD}/Week06_final.validation.json`});await fs.copyFile(FINAL,DELIVERY);await fs.writeFile(`${BUILD}/finalizer-result.json`,JSON.stringify(result,null,2));console.log(JSON.stringify({slideCount:slides.length,final:DELIVERY,render:RENDER},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
