import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const ROOT = '/Users/khairuladib/MATLAB-Drive/Kuliah/computational-physics-course';
const OUT = path.join(ROOT, 'Week01/.agent/lecture-slides/native-recovery/Week01_artifact-stage.pptx');
const OUT2 = path.join(ROOT, 'Week02/.agent/lecture-slides/native-recovery/Week02_artifact-stage.pptx');
const C = { navy:'#0B2B4C', charcoal:'#3F4B57', muted:'#697684', blue:'#2F6DB2', teal:'#2A9D9F', green:'#3E8E45', gold:'#C98A16', red:'#B3262E', pale:'#F4F8FC', pale2:'#F7F9FB', white:'#FFFFFF' };
const N = 'Nunito', M = 'IBM Plex Mono';
const none = {style:'solid',fill:'none',width:0};
function tx(s,t,p,st={}) { const q=s.shapes.add({geometry:'textbox',position:p,fill:'none',line:none}); q.text=t; q.text.style={typeface:N,fontSize:28,color:C.charcoal,alignment:'left',verticalAlignment:'top',autoFit:'none',insets:{top:0,right:0,bottom:0,left:0},...st}; return q; }
function box(s,p,fill=C.pale,stroke=C.blue) { return s.shapes.add({geometry:'roundRect',position:p,fill,line:{style:'solid',fill:stroke,width:2},borderRadius:'rounded-xl'}); }
function title(s,n,t,sub='') { if(n){tx(s,String(n),{left:1764,top:976,width:40,height:28},{fontSize:22,color:C.muted,alignment:'right'});} tx(s,t,{left:115,top:60,width:1580,height:92},{typeface:N,fontSize:68,bold:true,color:C.navy}); if(sub)tx(s,sub,{left:115,top:152,width:1580,height:44},{fontSize:30}); }
function steps(s,items,x=130,y=280,w=480) { items.forEach((a,i)=>{box(s,{left:x,top:y+i*104,width:w,height:76},i%2?C.pale2:'#EEF5FD',i%2?C.teal:C.blue);tx(s,`${i+1}. ${a}`,{left:x+24,top:y+i*104+19,width:w-48,height:38},{fontSize:28,bold:true,color:C.navy});}); }
function code(s,lines,x,y,w,h){box(s,{left:x,top:y,width:w,height:h},'#F7F9FB','#AAB4BE');tx(s,lines,{left:x+28,top:y+25,width:w-56,height:h-45},{typeface:M,fontSize:24,color:C.navy,breakLine:false});}
function note(s){s.speakerNotes.textFrame.setText('[Sources]\n- PHY4605 Week materials and retained course assets\n[/Sources]');s.speakerNotes.setVisible(true);}
function slide(d,n,t,sub,build){const s=d.slides.add();s.background.fill=C.white;title(s,n,t,sub);build(s);note(s);}
function deck1(){const d=Presentation.create({slideSize:{width:1920,height:1080}});slide(d,0,'Physics to arrays and plots','A vertical launch becomes a sequence of checked calculations',s=>{tx(s,'Question',{left:115,top:290,width:500,height:60},{fontSize:42,bold:true,color:C.blue});tx(s,'How can MATLAB calculate the ball’s height at many times and reveal the motion in one labelled plot?',{left:115,top:370,width:690,height:180},{fontSize:34});box(s,{left:980,top:270,width:650,height:430},'#EEF5FD',C.blue);tx(s,'launch → rise → peak → return',{left:1050,top:420,width:500,height:80},{fontSize:40,bold:true,color:C.navy});});
slide(d,1,'Start with the physical prediction','Upward is positive; gravity is constant; air resistance is neglected',s=>{steps(s,['At 0 s: y = 0 m','The ball rises and slows','The graph has one peak','It returns toward y = 0 m'],130,280,570);tx(s,'A graph is evidence only if it agrees with this physical story.',{left:900,top:440,width:700,height:90},{fontSize:36,bold:true,color:C.green});});
slide(d,2,'The model connects physics to calculation','Each variable carries a value and a unit',s=>{code(s,'y(t) = y0 + v0*t - 0.5*g*t^2',170,330,1020,120);steps(s,['y0 = 0 m','v0 = 20 m s⁻¹','g = 9.81 m s⁻²'],1350,300,360);});
slide(d,3,'A time array stores many sample moments','Use one position for every time value',s=>{code(s,'t_s = 0:0.5:4;',130,290,600,100);tx(s,'Index:   1      2      3      …      9',{left:130,top:500,width:1200,height:44},{typeface:M,fontSize:28,color:C.navy});tx(s,'Time:    0    0.5    1.0     …    4.0 s',{left:130,top:560,width:1200,height:44},{typeface:M,fontSize:28,color:C.navy});tx(s,'MATLAB indexing starts at 1.',{left:130,top:720,width:900,height:60},{fontSize:36,bold:true,color:C.red});});
slide(d,4,'Element-wise operators calculate every sample','The dot tells MATLAB to work value by value',s=>{code(s,'y_m = y0_m + v0_mps.*t_s - 0.5*g_mps2.*t_s.^2;',120,310,1550,120);tx(s,'Use .* and .^ when both sides contain arrays.',{left:120,top:510,width:1400,height:70},{fontSize:38,bold:true,color:C.blue});});
slide(d,5,'A labelled plot lets us test the prediction','Axes and units make the result interpretable',s=>{box(s,{left:250,top:280,width:1180,height:540},'#F7F9FB',C.navy);tx(s,'height y (m)',{left:320,top:350,width:260,height:44},{fontSize:28,bold:true});tx(s,'time t (s)',{left:860,top:740,width:240,height:44},{fontSize:28,bold:true});tx(s,'rises → peak → falls',{left:670,top:500,width:440,height:54},{fontSize:36,bold:true,color:C.green});});
slide(d,6,'Trace one value before trusting the whole array','At index 1, time is 0 s',s=>{code(s,'t_s(1) = 0\ny_m(1) = 0 + 20×0 - 0.5×9.81×0² = 0 m',140,330,1260,190);tx(s,'Known-value check: y(0) = 0 m ✓',{left:140,top:620,width:1000,height:70},{fontSize:40,bold:true,color:C.green});});
slide(d,7,'Modify one input and compare the physical result','A larger launch speed should increase the peak height',s=>{steps(s,['Keep y0 and g fixed','Change v0 only','Recalculate the array','Compare labelled curves'],130,280,540);tx(s,'Controlled comparison: change one thing, then explain one change in the graph.',{left:850,top:420,width:780,height:120},{fontSize:36,bold:true,color:C.blue});});
slide(d,8,'Common mistakes have visible clues','Classify the problem before changing the code',s=>{steps(s,['Missing dot operator','Wrong array index','Unlabelled graph','Unit or sign error'],130,280,560);tx(s,'Ask: is it a syntax, array, plotting, or physical-model defect?',{left:900,top:450,width:720,height:110},{fontSize:36,bold:true,color:C.red});});
slide(d,9,'The complete reasoning chain is reusable','Model → units → array → calculation → plot → check → explanation',s=>{tx(s,'The code is not the goal. The goal is a result you can explain and validate.',{left:180,top:350,width:1420,height:110},{fontSize:44,bold:true,color:C.navy});});
slide(d,10,'Checkpoint: read the graph physically','What should the curve show at launch, peak, and return?',s=>{tx(s,'Use the graph to support a claim about the ball’s motion—not just to report that it “looks right”.',{left:170,top:340,width:1460,height:120},{fontSize:40,color:C.charcoal});});
slide(d,11,'Exit ticket','Name one validation check and one unit you would inspect before submitting',s=>{tx(s,'Your evidence should connect the numerical output back to the physical model.',{left:180,top:380,width:1450,height:90},{fontSize:42,bold:true,color:C.green});});return d;}
function deck2(){const d=Presentation.create({slideSize:{width:1920,height:1080}});const content=[['Pseudocode, loops and debugging','Turn the vertical-launch model into a checkable sequence','How can MATLAB calculate one position at a time in a clear order?'],['Begin with a physical prediction','The ball rises, reaches one peak, then falls','At 0 s, y must be 0 m'],['Break the task into four jobs','Input → calculation → output → check','Each job has a clear physical purpose'],['Pseudocode maps the algorithm','Use plain language before MATLAB punctuation','Choose values; make time array; calculate height; plot; check y(0)'],['A for loop visits one array position at a time','The index connects t(k) with y(k)','k = 1, 2, 3, …, numel(t_s)'],['Trace the first two loop results','Trace values before running the full loop','0 s → 0 m; 0.5 s → 8.77375 m'],['Complete the one-line update','The calculation must use the matching index k','y_m(k) = y0_m + v0_mps*t_s(k) - 0.5*g_mps2*t_s(k)^2;'],['Modify one physical input','Change v0 only, then predict the change','A larger launch speed raises the peak'],['Debug from evidence, not guesses','Read the message, inspect the line, check values and units','A plausible graph can still hide a physics defect'],['Classify the defect before debugging','Syntax; array/index/operator; physical/logical','Each category needs a different check'],['Validation begins at the known initial value','The first computed position must be y(0) = 0 m','If the first value fails, stop and investigate'],['Interpret the final output physically','Explain rise, peak and descent using the model','The graph should agree with the prediction'],['Exit ticket','Write the next debugging action for a failed initial-value check','Model → algorithm → code → validation → explanation']];content.forEach((a,i)=>slide(d,i,a[0],a[1],s=>{if(i===3)steps(s,['Choose y0, v0 and g','Create the time array','Repeat the height calculation','Plot and check the result'],130,280,620);else if([4,5,6].includes(i))code(s,i===4?'for k = 1:numel(t_s)\n    % calculate y_m(k)\nend':i===5?'k = 1: t = 0 s, y = 0 m\nk = 2: t = 0.5 s, y = 8.77375 m':'y_m(k) = y0_m + v0_mps*t_s(k) - 0.5*g_mps2*t_s(k)^2;',120,310,1540,i===4?260:150);else {tx(s,a[2],{left:155,top:350,width:1480,height:150},{fontSize:42,bold:true,color:i===10?C.green:C.navy});box(s,{left:155,top:600,width:1320,height:90},i===9?'#FFF2F2':'#EEF5FD',i===9?C.red:C.blue);tx(s,i===9?'Evidence first: identify the defect category before editing.':'Use the vertical-launch model as the reference.',{left:190,top:625,width:1260,height:42},{fontSize:28,bold:true,color:C.charcoal});}}));return d;}
async function save(d,p){const b=await PresentationFile.exportPptx(d);await b.save(p);}
await fs.mkdir(path.dirname(OUT),{recursive:true});await fs.mkdir(path.dirname(OUT2),{recursive:true});await save(deck1(),OUT);await save(deck2(),OUT2);
